### PR TITLE
Send params as base64 encoded string

### PR DESCRIPTION
**Pull request by navFooh**
Removes all the `StateDecodeParams` calls to Lotus and send the parameters as base64 encoded string.
Let's discuss how to roll this out, but would be great to have this on calibrationnet so I can do some tests with the front-end.

### CODE REVIEW

**Review by ganzai-san — APPROVED** [review]

**Review by Schwartz10 — APPROVED** [review]
I'm assuming this was tested locally, but my one question would be about `base64` encoding `params` - are we double base64 encoding params?

I had assumed the params were _already_ base64 encoded (which is why we were passing them to `StateDecodeParams`) - but I see in this PR we commonly are base64'ing the params - maybe I'm confused and those actually start out as CBOR? 

If we're not double encoding params here, this is fine to squash & merge

**Comment by navFooh** [comment]
> I'm assuming this was tested locally, but my one question would be about `base64` encoding `params` - are we double base64

I haven't been able to run `graph` successfully. I can build the Docker image, but when I run the container it fails to connect to the database. I'm not sure where I can find the complete instructions to run the whole project locally, but since everything compiles properly I assume that there aren't any issues.

The params are byte arrays in Golang, so they're encoded to base64 strings.

**Review by ganzai-san — CHANGES_REQUESTED** [review]
I don't think we should remove unused properties. If you don't need them, don't ask for them client side. The graph will only resolve the gascost, receipt...etc if you ask for them.

**Comment by navFooh** [comment]
> I don't think we should remove unused properties. If you don't need them, don't ask for them client side. The graph will only resolve the gascost, receipt...etc if you ask for them.

The reason for this was to improve usability of the TypeScript types that are generated from the GraphQL schema.

For example, TypeScript creates a `Message` type based on the **full** `Message` object as defined in the schema. When selecting a subset of the `Message` properties, the query result does not pass as a valid `Message` object in TypeScript because it is missing some properties. 

We can work around this by manually defining the query result types, which is not that bad either. For example:
```
type GqlMessage = MessageQuery['message']
```
The `GqlMessage` type will then just contain the properties that were requested in our message query and we can use that type instead of the auto-generated `Message` type.

My initial feeling is that we should keep it as simple as possible for ourselves because I think we are the only clients of this server. So if we don't ever request the `version`, `gasCost` and `receipt` properties in `Message`, my intuition would be to remove them. But I'm fine with the other approach as well, so happy to revert the last commit if you feel strongly for keeping all the properties.

@Schwartz10 any thoughts on this?

**Comment by Schwartz10** [comment]
@navFooh i spoke with ganzai about it, and he made a good point about not having typescript warrant the flexibility of our graphql backend. Graphql is built so that we can just request any data we want - if we don't need it, simply don't request it, but it is conceivable that one time in the futuer we would want to execute the message query with those other queries included, and it would just be annoying to have to add that back and then fix all the types in a different way again in the future.

I'd vote to go with your second approach, defining the message type itself

**Review by ganzai-san — APPROVED** [review]

**Pull request merged**
